# fly.toml app configuration file generated for ortografe-server on 2024-01-08T17:01:18-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ortografe-server"
primary_region = "cdg"

[build]
  dockerfile = "site/deployment/Dockerfile"

[http_service]
# https://fly.io/docs/networking/services/
#
# Apparently, fly turns handles the TLS for us, so our server only ever sees http1.1, not
# http2. It seems that dream doesn't support http2 without TLS, so we can't request that
# the fly proxy talk to us this way. Maybe at some point we should turn off the proxying,
# although that'll probably involve figuring out a story for certificates.
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
